spring.application.name=sportswear
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/sportswear_db
spring.datasource.username=postgres
spring.datasource.password=123456
driver-class-name: org.postgresql.Driver
# Run
server.port=8080
# Migration
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG
# Swagger
springdoc.swagger-ui.path=/swagger-ui.html